---
name: "Setup → Amazon ECR"
description: "Setup the host for using an ECR registry"

inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS Region"
    required: true

outputs:
  registry:
    description: "Registry URL"
    value: ${{ steps.ecr-login.outputs.registry }}

runs:
  using: "composite"
  steps:
    # AWS credentials setup
    - id: aws-setup
      name: Setting up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id}}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    # Login to ECR
    - id: ecr-login
      name: Authenticating against ECR registry
      uses: aws-actions/amazon-ecr-login@v1
